# 5. 파이썬을 이용한 과학 계산

## 5.1 개요와 사전준비

### 5.1.1 개요

### 5.1.2 라이브러리 임포트

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
%precision 3

'%.3f'

## 5.2 넘파이를 이용한 계산 방법

### 5.2.1 인덱스 참조

데이터 참조

In [2]:
sample_array = np.arange(10)
print('sample_array', sample_array)

sample_array [0 1 2 3 4 5 6 7 8 9]


In [3]:
print(sample_array)
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [4]:
sample_array_slice[0:3] = 10
print(sample_array_slice)
print(sample_array)

# 슬라이싱은 원본 리스트의 원소 값도 변경한다는 점에 주의
# 원래 변수 값도 바뀌는 이유는 복사가 아니라 참조하기 때문

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


데이터 복사

In [9]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print(sample_array)
# copy해서 다른 object를 생성하면 원본 리스트의 원소는 변경되지 않음

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


불(boolean) 인덱스 참조

In [11]:
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [12]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [13]:
data[sample_names == 'a']
# 2차원 배열이므로 0번째와 네 번째 열이 추출

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

조건 제어

* numpy.where(조건 배열, X 데이터, Y 데이터)

In [14]:
cond_data = np.array([True, True, False, False, True])
x_array = np.array([1, 2, 3, 4, 5])
y_array = np.array([100, 200, 300, 400, 500])
print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


연습문제

In [15]:
# 5-1

In [16]:
# 5-2

In [17]:
# 5-3

### 5.2.2 넘파이를 이용한 연산 작업

중복 삭제

In [21]:
cond_data = np.array([True, True, False, False, True])

print(cond_data)
print(np.unique(cond_data))
print(cond_data) # inplace 안됨

[ True  True False False  True]
[False  True]
[ True  True False False  True]


범용 함수

: 모든 원소에 함수를 적용할 수 있는 기능



In [24]:
sample_data = np.arange(10)
print('원본 데이터 \t\t:', sample_data)
print('모든 원소의 제곱근 \t\t:', np.sqrt(sample_data))
print('모든 원소의 자연상수 지수함수 \t:', np.exp(sample_data))

원본 데이터 		: [0 1 2 3 4 5 6 7 8 9]
모든 원소의 제곱근 		: [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
모든 원소의 자연상수 지수함수 	: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


최소, 최대, 평균, 합계 계산

In [26]:
sample_multi_array_data1 = np.arange(9).reshape(3, 3)
print(sample_multi_array_data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
print('최소값\t:', sample_multi_array_data1.min())
print('최대값\t:', sample_multi_array_data1.max())
print('평균\t:', sample_multi_array_data1.mean())
print('합계\t:', sample_multi_array_data1.sum())

print('행 합계\t:', sample_multi_array_data1.sum(axis = 1))
print('열 합계\t:', sample_multi_array_data1.sum(axis = 0))

최소값	: 0
최대값	: 8
평균	: 4.0
합계	: 36
행 합계	: [ 3 12 21]
열 합계	: [ 9 12 15]


## 5.3 사이파이 응용